version: '3.10'

services:
  postgres:
    container_name: postgres_tasks
    image: postgres:16
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5432:5432"

  telegram_avtoban:
    build:
      context: .
      dockerfile: TelegramDockerfile
    command: ["dockerize", "-wait", "tcp://postgres_tasks:5432", "-timeout", "1m", "--", "python", "./main.py"]
    env_file:
      - ./telegram/.env
    volumes:
      - ./telegram/:/app
    depends_on:
      - postgres
    restart: always
